---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dashboard
  namespace: app-dashboard-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dashboard
  template:
    metadata:
      labels:
        app: app-dashboard
    spec:
      containers:
        - name: app-dashboard-backend
          image: acrcampdev01.azurecr.io/dev/app-dashboard:#__#IMAGE_TAG#__#
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: acrregistrydev
      tolerations:
        - key: worker
          operator: Equal
          value: "true"
          effect: NoSchedule
      nodeSelector:
        agentpool: workerpool01

---
apiVersion: v1
kind: Service
metadata:
  name: app-dashboard
  namespace: app-dashboard-dev
spec:
  selector:
    app: app-dashboard
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-dashboard
  namespace: app-dashboard-dev
  annotations:
    ingressClassName: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: process-efficiency-analyzer-dev.pwc.in
      http:
        paths:
          - pathType: Prefix
            path: /app-dashboard(/|$)(.*)
            backend:
              service:
                name: app-dashboard
                port:
                  number: 5000
  tls:
    - hosts:
        - process-efficiency-analyzer-dev.pwc.in
      secretName: process-efficiency-analyzer-domain-secret
